# Generated by Django 4.2.7 on 2023-11-06 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='Future date not allowed',
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 11, 21, 31, 248262), verbose_name='expiration date'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.datetime(2023, 11, 6, 11, 22, 31, 313567))), name='Future date not allowed'),
        ),
    ]
