# Generated by Django 4.2.7 on 2023-11-06 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_vote_future_date_not_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='Future date not allowed',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='date',
            new_name='vote_date',
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 11, 30, 54, 67023), verbose_name='expiration date'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(check=models.Q(('vote_date__lte', datetime.datetime(2023, 11, 6, 11, 31, 54, 133490))), name='Future date not allowed'),
        ),
    ]
