# Generated by Django 4.2.7 on 2023-11-06 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_vote_future_date_not_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='Future date not allowed',
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 11, 29, 51, 801717), verbose_name='expiration date'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.datetime(2023, 11, 6, 11, 30, 51, 871716))), name='Future date not allowed'),
        ),
    ]
