# Generated by Django 4.2.7 on 2023-11-06 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_vote_future_date_not_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='Future date not allowed',
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 11, 31, 38, 41929), verbose_name='expiration date'),
        ),
    ]
