# Generated by Django 4.2.6 on 2023-11-01 12:48

import datetime
from django.db import migrations, models
import polls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_choice_choice_text_alter_question_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, validators=[polls.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, validators=[polls.validators.validate_votes]),
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 12, 48, 31, 971269), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 12, 48, 31, 971269), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, unique=True, validators=[polls.validators.validate_text]),
        ),
    ]
