# Generated by Django 4.2.6 on 2023-11-01 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_question_exp_date_alter_question_pub_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='choice',
            name='Unique answers to question',
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 14, 24, 10, 170488), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 14, 24, 10, 170488), verbose_name='date published'),
        ),
    ]
