# Generated by Django 4.2.7 on 2023-11-04 16:49

import datetime
from django.db import migrations, models
import polls.validators


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_question_exp_date_alter_user_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 16, 49, 51, 472772), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=20, unique=True, validators=[polls.validators.validate_userid]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Guest', max_length=20, validators=[polls.validators.validate_text]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 16, 49, 51, 536785)),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('username__length__gte', 1)), name='username_length'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('userid__length', 20)), name='userid_length'),
        ),
    ]
