# Generated by Django 4.2.7 on 2023-11-04 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_question_exp_date_alter_user_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 38, 47, 713361), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 17, 38, 47, 777385)),
        ),
    ]
