# Generated by Django 4.2.7 on 2023-11-04 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_question_exp_date_alter_vote_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='Future votes not permitted',
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 18, 7, 26, 943758), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 18, 7, 27, 5775)),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.datetime(2023, 11, 4, 18, 7, 27, 5775))), name='Future votes not permitted'),
        ),
    ]
