# Generated by Django 4.2.7 on 2023-11-04 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_remove_vote_future_votes_not_permitted_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='Future votes not permitted',
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 18, 11, 27, 357059), verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 18, 11, 27, 419837)),
        ),
    ]
